In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('Diabetes.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2768 entries, 0 to 2767
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Id                        2768 non-null   int64
 1   Pregnancies               2768 non-null   int64
 2   Glucose                   2768 non-null   int64
 3   BloodPressure             2768 non-null   int64
 4   SkinThickness             2768 non-null   int64
 5   Insulin                   2768 non-null   int64
 6   BMI                       2768 non-null   float64
 7   DiabetesPedigreeFunction  2768 non-null   float64
 8   Age                       2768 non-null   int64
 9   Outcome                   2768 non-null   int64
dtypes: float64(2), int64(8)
memory usage: 216.4 KB

In [5]:
df.head()

,Id,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,1,6,148,72,35,0,33.6,0.627,50,1
1,2,1,85,66,29,0,26.6,0.351,31,0
2,3,8,183,64,0,0,23.3,0.672,32,1
3,4,1,89,66,23,94,28.1,0.167,21,0
4,5,0,137,40,35,168,43.1,2.288,33,1

In [6]:
df.isnull().sum()

Id                          0
Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [13]:
# replacing the 0 and 1 values in Outcome columns to Diabetic and Normal
df['Outcome'] = df['Outcome'].replace(1, 'Diabetic')
df['Outcome'] = df['Outcome'].replace(0, 'Normal')

In [14]:
df.head()

,Id,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,1,6,148,72,35,0,33.6,0.627,50,Diabetic
1,2,1,85,66,29,0,26.6,0.351,31,Normal
2,3,8,183,64,0,0,23.3,0.672,32,Diabetic
3,4,1,89,66,23,94,28.1,0.167,21,Normal
4,5,0,137,40,35,168,43.1,2.288,33,Diabetic

In [15]:
df.to_csv("cleaned_diabetes.csv", index=False)